### ISSUE TITLE
how can we check is ipv4 or ipv6 address ?

### ISSUE THREAD

**Issue by gsivaprabu** [pwnn/is.js#5]
how can we check is ipv4 or ipv6 address ?

# is valid ipv4 address ?

### 216.239.59.128

# is valid ipv6 address ?

### 3ffe:1900:4545:3:200:f8ff:fe21:67cf

**Comment by vanita5** [comment]
I'd suggest using regular expressions for validating IPv4 and IPv6.

**Comment by gsivaprabu** [comment]
This library have no options for validating ipv4 and ipv6 ?

**Comment by pwnn** [comment]
Hi @gsivaprabu, there's no such predicates for now, and probably never will be. I think those methods are rarely used, and you should extend `is.js` to add whatever predicates you want, it's [pretty easy](https://github.com/pwnn/is.js#writing-new-predicates).

If your task at hand is just checking IP addresses, check out this [library](https://www.npmjs.com/package/is-ip).
